config/routes.rb
MiloTest::Application.routes.draw do
  get "home/index"
  
  match 'milo' => 'home#milo'
  match 'milo_submit' => 'home#milo_submit'
  match 'milo_product_submit' => 'home#milo_product_submit'
  match 'milo_product' => 'home#milo_product'
  match 'milo_review' => 'home#milo_review'
  match 'milo_review_submit' => 'home#milo_review_submit'
  match 'milo_inventory' => 'home#milo_inventory'
  match 'milo_inventory_submit' => 'home#milo_inventory_submit'
  
  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def milo_submit
    url = "https://api.x.com/milo/v3/store_addresses?key=#{params[:api_key]}&zip_code=#{params[:zip_code]}"
    if params[:radius].nil? || params[:radius].blank?
      url += "&radius=10"
    else
      url += "&radius=#{params[:radius]}"
    end
    
    if !params[:merchant_ids].nil? && !params[:merchant_ids].blank?
      url += "&merchant_ids=#{params[:merchant_ids]}"
    end
    p url
    #store addresses API
    response_raw = (HTTParty.get url)["store_addresses"]
    #response_raw = response_raw[0..9] unless response_raw.size < 10
    @response = response_raw
    @url = url
  end
  
  def milo_product
  end
  
  def milo_review
    
  end
  
  def milo_inventory
    
  end
  
  def milo_inventory_submit
    if params[:product_id].nil? || params[:product_id].blank?
      if !params[:product_name].nil? && !params[:product_name].blank?
         product_response = JSON.parse(HTTParty.get("https://api.x.com/milo/v3/products?key=#{params[:api_key]}&q=#{params[:product_name]}&per_page=10"))
         product_id = (product_response["products"].first)["product_id"]
         base_url = "https://api.x.com/milo/v3/availability?key=#{params[:api_key]}&product_id=#{product_id}&zip_code=#{params[:zip_code]}"  
      end
    else
      base_url = "https://api.x.com/milo/v3/availability?key=#{params[:api_key]}&product_id=#{params[:product_id]}&zip_code=#{params[:zip_code]}"
    end
    p base_url
    
    response_raw = HTTParty.get base_url
    
    @response = response_raw
    @url = base_url
  end
  
  def milo_review_submit
    if params[:product_id].nil? || params[:product_id].blank?
      if !params[:product_name].nil? && !params[:product_name].blank?
         product_response = JSON.parse(HTTParty.get("https://api.x.com/milo/v3/products?key=#{params[:api_key]}&q=#{params[:product_name]}&per_page=10"))
         product_id = (product_response["products"].first)["product_id"]
         base_url = "https://api.x.com/milo/v3/reviews?key=#{params[:api_key]}&product_id=#{product_id}&page=0&per_page=1"  
      end
    else
      base_url = "https://api.x.com/milo/v3/reviews?key=#{params[:api_key]}&product_id=#{params[:product_id]}&page=0&per_page=1"
    end
    p base_url
    response_raw = HTTParty.get base_url
    p response_raw
    @response = response_raw
    @url = base_url
  end
  
  def milo_product_submit
    base_url = "https://api.x.com/milo/v3/products?key=#{params[:api_key]}&q=#{params[:query]}&per_page=10"
    if !params[:zip_code].nil? && !params[:zip_code].blank?
      base_url += "&zip_code=#{params[:zip_code]}"
    end
    if !params[:min_price].nil? && !params[:min_price].blank?
      base_url += "&min_price=#{params[:min_price]}"
    end
    if !params[:max_price].nil? && !params[:max_price].blank?
      base_url += "&max_price=#{params[:max_price]}"
    end
    if !params[:min_rating].nil? && !params[:min_rating].blank?
      base_url += "&min_rating=#{params[:min_rating]}"
    end
    if !params[:max_rating].nil? && !params[:max_rating].blank?
      base_url += "&max_rating=#{params[:max_rating]}"
    end
     if !params[:category_ids].nil? && !params[:category_ids].blank?
        base_url += "&category_ids=#{params[:category_ids]}"
      end
      if !params[:merchant_ids].nil? && !params[:merchant_ids].blank?
        base_url += "&merchant_ids=#{params[:merchant_ids]}"
      end
      if !params[:is_deal].nil? && !params[:is_deal].blank?
        base_url += "&is_deal=#{params[:is_deal]}"
      end
      if !params[:on_sale].nil? && !params[:on_sale].blank?
        base_url += "&on_sale=#{params[:on_sale]}"
      end
     #store addresses API
      p base_url
      response_raw = JSON.parse(HTTParty.get base_url)
      p response_raw
      #p nil.value
      #response_raw = response_raw[0..9] unless response_raw.size < 10
      @response = response_raw
      @merchants = response_raw["merchants"]
      @url = base_url
      
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def coderay(text)
    text.gsub(/\<code( lang="(.+?)")?\>(.+?)\<\/code\>/m) do
      content_tag("notextile", CodeRay.scan($3, $2).div(:css => :class))
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_milo_inventory_response.html.haml
.span-22.push-1
	/ %h3= "Results"
	%h3= "JSON stream dump"
	%p This shows the JSON dump of the response. Please note that, the JSON response is presented as an output for this end point as an illustration of what really happens behind the scenes. A callback can be written that handles the response stream.
	.milo-button
		= button_to "Milo Inventory API", milo_inventory_path
	#milo-results
		= render :partial => "inventory_json_output", :locals => {:response => response}

app/views/home/_milo_inventory_response_results.html.erb
<h3> What just went on? </h3>
<div class="docs-body">
	<p> The submit button triggered the following web request </p>
	<div class="code">
	<%= textilize("<pre>#{url}
	</pre>").html_safe %>
	</div>
	<p> The output response is different from the other end points. Instead of a JSON object, there is a series of JSON objects that are returned.  </p>
	<div class="code">
	<%= textilize(
		"<pre>
		merchant => {};
		location => {};
		result => {};
		</pre>"
	).html_safe%>	
	</div>
	<p> A stream of data comes in the above format and the connection is kept open until all the data is delivered. Programmatically, using this information becomes slightly harder than the other cases, where one JSON object or a list in some cases was delivered.</p>
	<p>If you are using Ruby, you can use the yajl gem to handle the JSON input stream. </p>
</div>

app/views/home/_milo_inventory_search.html.haml
.span-22
	.docs-title
		%h3= "Milo inventory (availability) search API"
	.docs-body
		%p This endpoint provides the information availability of a product. It accepts a product_id and returns availability information. Location is a mandatory field.
		= render :partial => "home/code/inventory_response_api"

app/views/home/_milo_product_form.html.haml
.span-8.push-1
	%h3= "Milo Product API"
	.milo_form
		= form_tag milo_product_submit_path, :method => 'post', :id => 'miloproductform', :remote => true do
			= label_tag 'API_KEY', "API KEY from devportal.x.com"
			%br/
			= text_field_tag "api_key", "#{MILO_API_KEY}", :size => 75
			
			%br/
			= label_tag 'query', "Product name eg., Blackberry Playbook"
			%br/
			= text_field_tag "query", '', :size => 75	
			%br/
			%h3= "Optional Fields"
			= label_tag 'zip', "Zip Code"
			%br/
			= text_field_tag "zip_code", '', :size => 75
			%br/
			= label_tag 'zip', "Radius"
			%br/
			= text_field_tag "radius", '10', :size => 75
			%br/
			= label_tag 'minprice', "Min Price (in cents) i.e., $33.95 = 3395"
			%br/
			= text_field_tag "min_price", '', :size => 75
			%br/
			= label_tag 'maxprice', "Max Price (in cents) i.e., $100.00 = 10000"
			%br/
			= text_field_tag "max_price", '', :size => 75
			%br/
			= label_tag 'minrating', "Min Rating (0..5) i.e., 2"
			%br/
			= text_field_tag "min_rating", '', :size => 75
			%br/
			= label_tag 'maxrating', "Max Rating (0..5) i.e., 5"
			%br/
			= text_field_tag "max_rating", '', :size => 75
			%br/
			= label_tag 'categoryids', "Comma separated category IDs i.e., 1,2,100"
			%br/
			= text_field_tag "category_ids", '', :size => 75
			%br/
			= label_tag 'merchantids', "Comma separated Merchant IDs i.e., 1,2,100"
			%br/
			= text_field_tag "merchant_ids", '', :size => 75
			%br/
			= label_tag 'onsale', "Is the Item On Sale? i.e., true"
			%br/
			= text_field_tag "on_sale", '', :size => 75
			%br/
			= label_tag 'isdeal', "Is the Item a Deal? i.e., true"
			%br/
			= text_field_tag "is_deal", '', :size => 75
			%br/
			= submit_tag "Submit"

app/views/home/_milo_product_search.html.haml
.span-22
	.docs-title
		%h3= "Milo product search API"
	.docs-body
		%p= "The product search returns detailed information about a product. Location parameters are optional. You can use the same location parameters as explained in the store address API section. Other optional values here are pagination options and sorting details."
		= render :partial => "home/code/product_response_api"

app/views/home/_milo_review_response.html.haml
.span-22.push-1
	/ %h3= "Results"
	.milo-button
		= button_to "Milo Reviews API", milo_review_path
	#milo-results
		- if !response.nil?
			%h3= "Showing the top review"
			
			.review-body
				.review-stars
					%p= "#{'*'*Integer(response["reviews"].first["primary_rating"])}"
				.review-title
					%p= "#{response["reviews"].first["title"]}"
				.review-text
					%p= "#{strip_tags(response["reviews"].first["review_text"])}"

app/views/home/_milo_reviews_search.html.haml
.span-22
	.docs-title
		%h3= "Milo reviews API"
	.docs-body
		%p= "This endpoint returns a list of reviews for a product. A product ID can be used to query the reviews. Again, similar to the other store address API, it is more beneficial to use this in combination with the product search API, where the product_id is returned to us in the output response."
		= render :partial => "home/code/reviews_response_api"
		
		

app/views/home/_milo_store_address.html.haml
.span-22
	.docs-title
		%h3= "Milo store addresses API"
	.docs-body
		%p= "The store address endpoint returns information about stores in a particular location. This can be used to get a list of all merchants around an area or specific merchants, if their merchant ID is known."
		= render :partial => "home/code/store_address_api_1"
		
		

app/views/home/_milo_store_response_results.html.erb
<h3> What just went on? </h3>
<div class="docs-body">
	<p> The submit button triggered the following web request </p>
	<div class="code">
	<%= textilize("<pre>#{url}
	</pre>").html_safe %>
	</div>
	<p> The output response contains the following fields that can be parsed in the way we want. </p>
	<div class="code">
	<%= textilize(
		"<pre>
		address_id: integer;
		store_id: text;
		descriptor: text;
		street: text;
		city: text;
		region: text;
		country: text;
		longitude: signed float;
		latitude: signed float;
		hours: object;
		merchant_id: integer;
		merchant_name: text;
		</pre>"
	).html_safe%>	
	</div>
	<p> If you look at the results, top ten are shown as a demonstration. To be honest, getting a list of all the stores in an area is kind of meaningless unless it translates to something useful. For instance, you can create a visualization of which stores are open, when? Or we can mash this API with other product specific APIs to provide more information about a store carrying a product. For instance, in a product search, you will notice that a product availability can be queried, which returns a merchant_id as a response. That merchant_id can be fed into the store address end point to get more accurate store information. </p>
	
</div>

app/views/home/code/_inventory_response_api.html.erb
<div class="code">
<%= textilize('<pre>HTTParty.get http://api.x.com/milo/v3/availability?key=KEY&product_id=9418020&zip_code=78759
</pre>').html_safe %>
</div>
<br/>
<p><%= "You can replace the zip_code field by an ip_address field or latitude and longitude pair"%></p>
<div class = "code">
<%= textilize('<pre>HTTParty.get https://api.x.com/milo/v3/availability?key=KEY&ip_address=190.120.23.178&radius=8.5</pre>').html_safe %>
</div>
<br/>
<p> This endpoint lets you specify an optional call_back, which gets routed to your controller action, and can be used to process the results. </p>

app/views/home/code/_product_response_api.html.erb
<div class="code">
<%= textilize('<pre>HTTParty.get https://api.x.com/milo/v3/products?key=KEY&q=blackberry&zip_code=78759&per_page=2
</pre>').html_safe %>
</div>
<br/>
<p> The input response can contain the following fields. </p>
<div class="code">
<%= textilize(
	"<pre>
	location: zip_code, ip_address, latitude and longitude pair;
	query: text;
	min_price: positive integer;
	max_price: positive integer;
	min_rating: integer [0,5];
	max_rating: integer[0,5];
	category_ids: integers comma seperated;
	merchant_ids: integers comma seperated;
	on_sale: true or false;
	on_deal: true or false;
	
	sort_by: price, rating, relevance (default);
	page: integer;
	per_page: integer;
	</pre>"
).html_safe%>	
</div>
<p>Except for the query, the other fields are optional.</p>

app/views/home/code/_reviews_response_api.html.erb
<div class="code">
<%= textilize('<pre>HTTParty.get https://api.x.com/milo/v3/reviews?key=KEY&product_id=16262&page=1&per_page=2
</pre>').html_safe %>
</div>
<br/>
<p> The input response can contain the following fields that can be parsed in the way we want. As you can note, location is not allowed. The important attribute is the product_id</p>
<div class="code">
<%= textilize(
	"<pre>
	product_id: integer;
	page: integer;
	per_page: integer;
	</pre>"
).html_safe%>	
</div>
<p>The pagination fields are optional</p>

<h3> Mashup </h3>
<p>I have taken the opportunity to show how to mashup the other end points to get meaningful information easily. For instance, if I want to get the reviews for some blackberry products, there is no way I want to take the trouble of finding the product id. It is actually painful. However, I know that I can get the product_id readily for free using the product search API or endpoint. </p>
<p> The field for product name, does precisely this. It takes the product name and uses it to find a product ID.</p>
<div class="code">
	<pre>
def milo_review_submit
  if params[:product_id].nil? || params[:product_id].blank?
    if !params[:product_name].nil? && !params[:product_name].blank?
       product_response = JSON.parse(HTTParty.get("https://api.x.com/milo/v3/products?key=#{params[:api_key]}&q=#{params[:product_name]}&per_page=10"))
       product_id = (product_response["products"].first)["product_id"]
       base_url = "https://api.x.com/milo/v3/reviews?key=#{params[:api_key]}&product_id=#{product_id}&page=0&per_page=1"  
    end
  else
    base_url = "https://api.x.com/milo/v3/reviews?key=#{params[:api_key]}&product_id=#{params[:product_id]}&page=0&per_page=1"
  end
  response_raw = HTTParty.get base_url
  @response = response_raw
  @url = base_url
end
</pre>
</div>

app/views/home/code/_store_address_api_1.html.erb
<div class="code">
<%= textilize('<pre>HTTParty.get https://api.x.com/milo/v3/store_addresses?key=KEY&zip_code=94040&radius=8.5&merchant_ids=1792
</pre>').html_safe %>
</div>
<br/>
<p><%= "You can replace the zip_code field by an ip_address field or latitude and longitude pair"%></p>
<div class = "code">
<%= textilize('<pre>HTTParty.get https://api.x.com/milo/v3/store_addresses?key=KEY&ip_address=190.120.23.178&radius=8.5</pre>').html_safe %>
</div>
<br/>
<p> As you can see, the merchant_id is an optional field. If that information is known, this query can be more targeted. For instance, you can find all the "Target" stores in a particular area and information about them like the store hours and address. </p>
<p> But, as a developer I feel that the value of this API lies in the mashup with the product API, which is super valuable. You will see a live example as you browse that particular endpoint. </p>

app/views/home/index.html.haml
#main
	.span-22
		.head-banner
			%h2
				= "A experimental documentation of Milo API."
				= " Do you like it? "
				= render :partial => "tweet"
			%br/
			%h2
				= "Have more ideas on how to make this more awesome? Talk to me on Twitter "
				= link_to "@saranyan", "http://twitter.com/saranyan", :target => "_blank"

	#content
		.span-20
			.sidebar
				.span-4	
					%ul
						%li
							%h3= link_to "Milo", root_path, :remote => true
	
			/ = render :partial => "setpay/simple_payments"
			.fields
				.pull-1
					#fields
						= render :partial => "milo_form"
			.fields-doc
				.push-1
					#fields-doc
						= render :partial => "milo_buttons"
	.span-22
		
		.foot-banner
		.push-1
			.footer
				#doc
					= render :partial => "milo_store_address"
					

app/views/home/milo.html.haml
#main
	.span-22
		.head-banner
			%h2
				= "A experimental documentation of Milo API."
				= " Do you like it? "
				= render :partial => "tweet"
			%br/
			%h2
				= "Have more ideas on how to make this more awesome? Talk to me on Twitter "
				= link_to "@saranyan", "http://twitter.com/saranyan", :target => "_blank"

	#content
		.span-20
			.sidebar
				.span-4	
					%ul
						%li
							%h3= link_to "Milo", root_path, :remote => true
	
			/ = render :partial => "setpay/simple_payments"
			.fields
				.pull-1
					#fields
						= render :partial => "milo_form"
			.fields-doc
				.push-1
					#fields-doc
						= render :partial => "milo_buttons"
	.span-22
		.foot-banner
		.push-1
			.footer
				#doc
					= render :partial => "milo_store_address"

app/views/home/milo_inventory.js.erb
$("#fields").html("<%= escape_javascript(render :partial => "milo_inventory_form")%>")
$("#fields-doc").html("<%= escape_javascript(render :partial => "milo_buttons")%>")
$("#doc").html("<%= escape_javascript(render :partial => "milo_inventory_search", :locals => {:url => @url})%>")

app/views/home/milo_product_submit.js.erb
$("#content").html("<%= escape_javascript(render :partial => "milo_product_response", :locals => {:response => @response, :merchants => @merchants})%>")
$("#doc").html("<%= escape_javascript(render :partial => "milo_product_response_results", :locals => {:url => @url})%>")

app/views/home/milo_review.html.haml
#main
	.span-22
		.head-banner
			%h2
				= "A experimental documentation of Milo API."
				= " Do you like it? "
				= render :partial => "tweet"
			%br/
			%h2
				= "Have more ideas on how to make this more awesome? Talk to me on Twitter "
				= link_to "@saranyan", "http://twitter.com/saranyan", :target => "_blank"

	#content
		.span-20
			.sidebar
				.span-4	
					%ul
						%li
							%h3= link_to "Milo", root_path, :remote => true
	
			/ = render :partial => "setpay/simple_payments"
			.fields
				.pull-1
					#fields
						= render :partial => "milo_review_form"
			.fields-doc
				.push-1
					#fields-doc
						= render :partial => "milo_buttons"
	.span-22
		.foot-banner
		.push-1
			.footer
				#doc
					= render :partial => "milo_reviews_search"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiloTest</title>
	<%= stylesheet_link_tag 'blueprint/screen', :media => "screen, projection" %>
	<%= stylesheet_link_tag 'blueprint/print', :media => "print" %>
	<%= stylesheet_link_tag 'jquery-ui', :media => "screen, projection, print"%>
	<!-- <link href='http://fonts.googleapis.com/css?family=Goudy+Bookletter+1911' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Raleway:100' rel='stylesheet' type='text/css'> -->
		<link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Raleway:100' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<meta property="og:title" content="Milo API Dashboard " />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="http://miloapi.herokuapp.com" />
	<meta property="og:image" content="http://www.paypal-labs.com/xbus/img/logo_x.commerce.jpg" />
	<meta property="og:site_name" content="Milo API Dashboard by Saranyan" />
	<meta property="fb:admins" content="1044610097" />
</head>
<body>
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=153818704722810";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
<%= yield %>

</body>
</html>